### ISSUE TITLE
Update the literary secretaries for this year

### ISSUE THREAD

**Issue by Signior-X** [KamandPrompt/Gymkhana-IITMandi#27]
For this year, these the coordies
Writing Cordinator
Ridhi Ratan - B19192 - 85297 73524
V Madhumita - B19202- 6362 985 890

Debating coordinator
Devansh kochar - B19245 - 9928036846
Yuvraj sing bishnoi - B19063 - 87007 61867

Quizzing coordinator
Raman soni - B18134 -  94614 06697
Anwesh Das  - B17116 - 7807554586

You ha to update the details in literary.html page.

**Comment by sauravshub1** [comment]
I want to try to solve the issue

**Comment by Signior-X** [comment]
Yeah go ahead!

Sorry that is contacts.html not literary.html

**Comment by vsvipul** [comment]
Closing as fixed now.
