### ISSUE TITLE
Make contacts page responsive.

### ISSUE THREAD

**Issue by vsvipul** [KamandPrompt/Gymkhana-IITMandi#29]

**Comment by prashant280920** [comment]
i want to work on this issue but for this plz merge the issue 32 so that i can work on the updated contacts.

**Comment by vsvipul** [comment]
@prashant280920  work on this now.

**Comment by vsvipul** [comment]
![image](https://user-images.githubusercontent.com/21038781/96250422-73793380-0fcc-11eb-8ae6-3c4e38283474.png)
Fix the empty space after research. Tabs hsould be centre aligned @prashant280920  @Signior-X

**Comment by Signior-X** [comment]
Okay sure!
Just as soon we get time!

**Comment by Signior-X** [comment]
till then I have made it centered.
Check @vsvipul now

**Comment by vsvipul** [comment]
@Signior-X  even the text is centred now in the table. only the tabs should be centred not the  table text. please fix.

**Comment by Signior-X** [comment]
okay will fix this now.

**Comment by Signior-X** [comment]
fixed this... check now!
