### ISSUE TITLE
Update the Academic Secy Page as suggested

### ISSUE THREAD

**Issue by Signior-X** [KamandPrompt/Gymkhana-IITMandi#31]
He asked to have some details, so just add that.
PM or comment here for more info.

**Comment by iitianpreetam** [comment]
Yes, I am willing to do this.

**Comment by Signior-X** [comment]
Ya sure go ahead @iitianpreetam 

I will give rest of the details to you.

**Comment by vsvipul** [comment]
Closing this now.
