### ISSUE TITLE
Make changes to contacts page

### ISSUE THREAD

**Issue by vsvipul** [KamandPrompt/Gymkhana-IITMandi#32]
1. In Technical and Cultural, remove FA email IDs and add Club Email IDs, just after the name of the club. Also remove the empty column between the contact no and fa. Also, remove anu empty rows.
2.  Update research contacts as well.

**Comment by Signior-X** [comment]
I feel this has been done.... 
Should this issue be closed now?

**Comment by vsvipul** [comment]
Looks good changes to reasearch society contacts left.

**Comment by vsvipul** [comment]
ACM | Kartik Kathuria | b18118@students.iitmandi.ac.in | 7982453395 | Dr. Manas Thakur | manasthakur@iitmandi.ac.in
IEEE | Manish Sharma | b17126@students.iitmandi.ac.in | 9511560530 | Dr. Amit Kumar Singha | amit@iitmandi.ac.in
ACM | Vyom Goel | b18093@students.iitmandi.ac.in | 9816790032 | Dr. Manas Thakur | manasthakur@iitmandi.ac.in
ACM | Kairav Bansal | b18062@students.iitmandi.ac.in | 9988154700 | Dr. Manas Thakur | manasthakur@iitmandi.ac.in

**Comment by vsvipul** [comment]
@Signior-X  remind to remove the above comment after it is updated.

**Comment by Signior-X** [comment]
okay sure
@prashant280920 would you continue this one also?

**Comment by prashant280920** [comment]
ok i will do this
