### ISSUE TITLE
Add society website link in Technical section 

### ISSUE THREAD

**Issue by vsvipul** [KamandPrompt/Gymkhana-IITMandi#35]
A link to sntc website - iitmandi.co.in would be good for navigation and discovery. Can be placed under "Club Contacts" link to open on a new page.

**Comment by vsvipul** [comment]
Change the text to "Society Website" , as we will have websites for other societies later as well.

**Comment by vsvipul** [comment]
@prashant280920

**Comment by prashant280920** [comment]
ok i will do this
