### ISSUE TITLE
More dropdown in the navbar should be more mobile friendly

### ISSUE THREAD

**Issue by vsvipul** [KamandPrompt/Gymkhana-IITMandi#39]

**Comment by prashant280920** [comment]
i just changed the location of drop down box for mobile view.
![2020-12-07 (1)](https://user-images.githubusercontent.com/60234231/101380041-03f03800-38db-11eb-9dc0-941b41ac9666.png)

**Comment by prashant280920** [comment]
I am also thinking about some animation in More dropdown box.  Is animation will be better? @vsvipul @Signior-X

**Comment by Signior-X** [comment]
You can give a try :+1: It will be a plus in the PR!
