### ISSUE TITLE
Add Btech 2020 Branch representatives on senate page

### ISSUE THREAD

**Issue by Signior-X** [KamandPrompt/Gymkhana-IITMandi#49]
On the senate page, the btech 2020 branch representatives are not there. They need to be added.

The details are given here https://docs.google.com/spreadsheets/d/1KpYtBwer-tB9lmRpj792B00o9fJww2tqIRtA6sgHq9k/edit#gid=0

Only Btech 2020 ones should be added to fix this issue.

**Comment by Anirudh-GH** [comment]
Can i work on this issue

**Comment by Ritam727** [comment]
I would try to work on this

**Comment by Signior-X** [comment]
@Anirudh-GH you can update the Btech 2019 members 
the issue is almost similar
