### ISSUE TITLE
Show "1 commit" instead of "1 commits" on contributors page

### ISSUE THREAD

**Issue by Signior-X** [KamandPrompt/Gymkhana-IITMandi#53]
![image](https://user-images.githubusercontent.com/56730716/112725695-94609000-8f3f-11eb-89a7-52fc234b9a39.png)

As seen in this screeshot, `1 commits` does not look good, it should be `1 commit`.

This logic is generated by javascript, so something can be tweaked there to have a condition. The specific code is currently [here](https://github.com/KamandPrompt/Gymkhana-IITMandi/blob/d5453ceae7591a20c427dc05680d352c304784be/contributors.html#L138)

**Comment by vsthecoder** [comment]
Working on it.

**Comment by Ritam727** [comment]
Trying to solve the issue
