### ISSUE TITLE
Add "Want to contribute" with github repo link on contributors page

### ISSUE THREAD

**Issue by Signior-X** [KamandPrompt/Gymkhana-IITMandi#54]
In the `contributors.html` page, add something, so that if someone wants to contribute can find the Github repo and can contribute or report an issue.

**Comment by Godwindaniel10** [comment]
hi, I will be so glad to work on this.  can i go ahead?

**Comment by Godwindaniel10** [comment]
The GitHub link icon on the contributor's profile should Open the linked document in a new window or tab 

solved this using the (      target="_blank"   ) attribute

**Comment by Signior-X** [comment]
> hi, I will be so glad to work on this. can i go ahead?

Sure go ahead!

**Comment by Signior-X** [comment]
> The GitHub link icon on the contributor's profile should Open the linked document in a new window or tab
> 
> solved this using the ( target="_blank" ) attribute

Yeah that is a good issue fix. Although there wasn't any issue related to it. So, you can create a new issue and and start working on it and make a PR. 

Sure go ahead! This will also be a very nice change.

**Comment by Godwindaniel10** [comment]
@Signior-X on it.........
