### ISSUE TITLE
Make the photos circle instead of oval on home page

### ISSUE THREAD

**Issue by Signior-X** [KamandPrompt/Gymkhana-IITMandi#55]
![image](https://user-images.githubusercontent.com/56730716/112726100-9f1c2480-8f41-11eb-977e-1af9b321c1b4.png)

As can be seen in the image, the photos are oval in shape. They should be a perfect circle. For that, in the CSS, height should also need to be mentioned and with the same value as width.

Hint: Inspect the element and try playing with CSS adding `height: 150px` and then find where to add this in the code.

**Comment by Godwindaniel10** [comment]
@Signior-X , to add to that ,   he/she can add ( height: 150px and width: 150px ) ;

**Comment by Signior-X** [comment]
yes, you can try this. Would love to have a PR from you side.
btw are you working on this issue?

If you are working, I would suggest first complete the other issue. Then do this one.

**Comment by Godwindaniel10** [comment]
@Signior-X , right, when I am done fixing other issues, then I am coming to this...

**Comment by Ritam727** [comment]
Would be working on this issue now
