### ISSUE TITLE
The GitHub link icon on the contributor's profile should Open the linked document in a new window or tab

### ISSUE THREAD

**Issue by Godwindaniel10** [KamandPrompt/Gymkhana-IITMandi#57]

**Comment by Signior-X** [comment]
Great!

**Comment by gd-codes** [comment]
I can fix this.

**Comment by Signior-X** [comment]
SURE, go ahead. Just after commenting, you can start working.

**Comment by Signior-X** [comment]
> I can fix this.

Sorry, there is already a PR related to this. You can try #58 
Solving that one will be really appreaciated.

**Comment by gd-codes** [comment]
Ok sure, np.
