### ISSUE TITLE
Add rel="noopener noreferrer" to the target="_none" links on Technical page

### ISSUE THREAD

**Issue by Signior-X** [KamandPrompt/Gymkhana-IITMandi#67]
On the technical page, see this line https://github.com/KamandPrompt/Gymkhana-IITMandi/blob/44604a306d72c52b23e5af3ec75daf7084c238c3/technical.html#L109

Add `rel="noopener noreferrer"` to this.

**Comment by i0girish** [comment]
i am branching this one

**Comment by i0girish** [comment]
trying this one.

**Comment by i0girish** [comment]
I am working on it
