### ISSUE TITLE
Add rel="noopener noreferrer" to the target="_none" links on Senate page

### ISSUE THREAD

**Issue by Signior-X** [KamandPrompt/Gymkhana-IITMandi#68]
On the Senate page, see this line https://github.com/KamandPrompt/Gymkhana-IITMandi/blob/44604a306d72c52b23e5af3ec75daf7084c238c3/senate.html#L105

Add `rel="noopener noreferrer"` to this.

**Comment by batman14-s** [comment]
I'm working on it...
