### ISSUE TITLE
Move news to the dropdown menu

### ISSUE THREAD

**Issue by Signior-X** [KamandPrompt/Gymkhana-IITMandi#73]
The `news` tab here on all the pages
![image](https://user-images.githubusercontent.com/56730716/112752979-5cb32000-8ff3-11eb-87aa-2c37ae9e2eb4.png)

news has become quite old and now it doesn't get updated. I think moving it to `more` dropdown will be better.

**Comment by DineshKoushik** [comment]
@Signior-X , I'll do this
