### ISSUE TITLE
Update Btech 2018 CSE Branch representative on senate page

### ISSUE THREAD

**Issue by Strikerzee** [KamandPrompt/Gymkhana-IITMandi#79]
The branch representative of CSE 2018 got changed.

https://docs.google.com/spreadsheets/d/1KpYtBwer-tB9lmRpj792B00o9fJww2tqIRtA6sgHq9k/edit#gid=0
So from this doc,

Update Ankit Baluni with Mohib Qureshi
The details are in the doc, so do update the contacts accordingly. And keep the order of branches as such.

Hint: Changes will be in senate.html page

**Comment by Ritam727** [comment]
Will be working on it

**Comment by Signior-X** [comment]
#80 solved
